language: python
python:
  - "3.6"
  - "3.7"
# command to install dependencies
install:
# add new stuff to requirements file, not here
  - pip install -r requirement.txt
# command to run tests
script:
  - python -m pytest --cov=gastop/

after_success:
  - coveralls

notifications:
    slack:
      rooms:
        - princetonmae:MyikIXs3nE7eGCiIODO5VDxK
      on_failure: always
      on_success: change
